### PR TITLE
Remove the rest of the important tags and make modifications in stylesheet.

### PR DESCRIPTION
**Pull request by yirano**

### CODE REVIEW

**Comment by ebukaume** [comment]
Hi @yirano :wave:

Kudos on your efforts so far. Let's get a few things out of the way and get you on the green. :wink: 

- [ ] It contains Sign in and Subscribe links.
- [ ] The project has a descriptive README.md 
- Why does your social media icons disappear at smaller viewports?

You can use this [template](https://github.com/othneildrew/Best-README-Template) to make your README more descriptive. Please note that this is very important.

[OPTIONAL]
- I noticed you have too much space on either side of the main content unlike on the main NewsWeeks page. See [here](http://prnt.sc/pbx1s2) and compare with [this](https://www.newsweek.com/)

**Kindly submit another code review request after fixing these issues.** :v:

**Comment by yirano** [comment]
I have made some adjustments in the footer and have figured out the bug causing the social media icons to disappear on smaller screens. In addition to that, I have also styled the last two elements as well as minor adjustments to the general layout. 

The README.md file is more descriptive in the fitting manner of this project as well.

**Comment by yirano** [comment]
The overflow that caused the empty space on the right side of the page was caused by a absolute re-positioning of an image. This was modified to remove the extra white space.

**Comment by ebukaume** [comment]
HI @yirano :wave: 

kudos on your efforts so far :muscle:. However, it appears you forgot to effect some changes I requested earlier. I understand the pressure can be overwhelming some times but please kindly fix the issue as **they are part of the minimum requirements for the project.** I will list all pending requirements below for ease of reference.

**Navigation bar**
- [ ] It contains the current date.
- [ ] It contains Sign in and Subscribe links. (**_It seems yours disappear on large screens_**)

**CSS**
- [ ] No `!important` overusing (You can reference [this article](https://speckyboy.com/good-bad-css-practices) for support).

**Kindly submit another code review request form after you made those changes.**

**Happing coding** :v:

**Comment by yirano** [comment]
The date and links were positioned below the header, which blended right into the white of the body. I also made minor width adjustments to an image that was overflowing outside its container and cleaned the stylesheet.

**Comment by ebukaume** [comment]
Hi @yirano :wave: 

> The date and links were positioned below the header, which blended right into the white of the body. I also made minor width adjustments to an image that was overflowing outside its container and cleaned the stylesheet.

Compare [your work](https://raw.githack.com/yirano/mv-07-bootstrap-newsweek/newsweek-final/src/index.html) with the [Newsweek site](https://www.newsweek.com/) and observe that yours is not showing the **date on the left** and **sign in & subscribe links on the right** in the **Navigation bar**.

**_Yours_** :point_down: 
yirano-nav

_**Theirs**_ :point_down: 
newsweek-nav

Also, I still see 2 instances of `important` in your CSS. Can you fix those too? 

**Please note that these are required before this project can be approved:**

**Navigation bar**
- [ ] It contains the current date.
- [ ] It contains Sign in and Subscribe links. (_**It seems yours disappear on large screens**_)

**CSS**
  No `!important` overusing (You can reference this [article](https://speckyboy.com/good-bad-css-practices) for support).

**Kindly submit another review request after fixing the above issues.** :v:

**Comment by yirano** [comment]
> Hi @yirano 👋
> 
> > The date and links were positioned below the header, which blended right into the white of the body. I also made minor width adjustments to an image that was overflowing outside its container and cleaned the stylesheet.
> 
> Compare [your work](https://raw.githack.com/yirano/mv-07-bootstrap-newsweek/newsweek-final/src/index.html) with the [Newsweek site](https://www.newsweek.com/) and observe that yours is not showing the **date on the left** and **sign in & subscribe links on the right** in the **Navigation bar**.
> 
> **_Yours_** 👇
> yirano-nav
> 
> _**Theirs**_ 👇
> newsweek-nav
> 
> Also, I still see 2 instances of `important` in your CSS. Can you fix those too?
> 
> **Please note that these are required before this project can be approved:**
> 
> **Navigation bar**
> 
> * [ ]  It contains the current date.
> * [ ]  It contains Sign in and Subscribe links. (_**It seems yours disappear on large screens**_)
> 
> **CSS**
> No `!important` overusing (You can reference this [article](https://speckyboy.com/good-bad-css-practices) for support).
> 
> **Kindly submit another review request after fixing the above issues.** ✌️

I had to use the !important to override the bootstrap setting. It wouldn't let me adjust what I needed to otherwise.

The dates and links are showing on my end... So I'm a little confused right now. I'll look into that further but it's clearly showing on my end.

scrnli_9_28_2019_9-05-28 PM

**Comment by yirano** [comment]
scrnli_9_28_2019_9-10-17 PM

I used your method by going into raw.githack.com, and I'm seeing the dates clearly marked there as well. Perhaps it's something on your end? I will also check on a bigger screen to confirm.

**Comment by yirano** [comment]
@ebukaume  -- Please check above comment.

This screenshot is from my iMac. The date and links are showing in both my iMac and MacBook so I think the error is on your end. 

I have removed the important tags in my stylesheet and have made adjustments.

**Comment by ebukaume** [comment]
Hi @yirano 

I wonder where the problem is coming from. I am using Chrome, by the way.

Please, see if you can reproduce the error and see if you can fix it.

**Comment by yirano** [comment]
@ebukaume , I am also using Chrome and it's showing on both of my iMac and MacBook.

**Comment by ebukaume** [comment]
> @ebukaume -- Please check above comment.
> 
> This screenshot is from my iMac. The date and links are showing in both my iMac and MacBook so I think the error is on your end.
> 
> I have removed the important tags in my stylesheet and have made adjustments.

Nice, please kindly submit another review request. :v:

**Comment by ebukaume** [comment]
Hi @yirano :wave: 

Nice work! You have really done a good job with this project. 

:+1: :+1: :+1: Well done. **You should go ahead and merge this branch into master**. But please make the **sign in** in the Navigation bar to be a link before you merge.

Good luck on your next project :heart:

**Pull request merged**
